### ISSUE TITLE
error with new plugin installation

### ISSUE THREAD

**Issue by Alexey-T** [veksha/cuda_hotspots#1]
![Screenshot from 2024-01-06 12-51-14](https://github.com/veksha/cuda_hotspots/assets/4154978/48e3f3ea-f0ca-4f26-900a-ea5c804b1a82)

**Comment by veksha** [comment]
please, provide your `history files.json`. i'm interested in why it has no `bookmarks` key.

![image](https://github.com/veksha/cuda_hotspots/assets/275333/493885b6-a0b6-489b-b477-7102f8f966ee)

**Comment by Alexey-T** [comment]
key is appeared only 2 min ago.
```
  "bookmarks" : {},
```
before I did not have it!

**Comment by veksha** [comment]
fixed: https://github.com/veksha/cuda_hotspots/commit/1c46d9b6cd302a5dd1805048d69d0a83d6e1fae2
