### ISSUE TITLE
toolbar icons

### ISSUE THREAD

**Issue by Alexey-T** [veksha/cuda_hotspots#14]
https://www.iconfinder.com/search?q=refresh
and
https://www.iconfinder.com/search?q=git

have more simple icons. if you are OK with current ones- ok too.

**Comment by veksha** [comment]
can't use them for free. if you find icons that will look good on light/dark themes and they are completely free, let me know.
current icons are from Lazarus and they are free.

**Comment by Alexey-T** [comment]
[toolbar_main.zip](https://github.com/veksha/cuda_hotspots/files/13853391/toolbar_main.zip)

from Laz too!

**Comment by Alexey-T** [comment]
better icos?

[toolbar_main.zip](https://github.com/veksha/cuda_hotspots/files/13853405/toolbar_main.zip)

from Laz too

**Comment by Alexey-T** [comment]
from laz too

better?

[i.zip](https://github.com/veksha/cuda_hotspots/files/13853414/i.zip)


![collect](https://github.com/veksha/cuda_hotspots/assets/4154978/8e56d4d5-4fcf-4432-87ca-c7671c050320)
![untracked](https://github.com/veksha/cuda_hotspots/assets/4154978/c0ae8cc0-ac9e-4adc-8823-6147a14ce8a4)

**Comment by veksha** [comment]
yes. good looking on all themes.

**Comment by Alexey-T** [comment]
let's use em.

**Comment by veksha** [comment]
uploaded
