### ISSUE TITLE
made 4 new bookmarks w/o saving the file (and saving bookmarks history) - new bookmarks are missed

### ISSUE THREAD

**Issue by Alexey-T** [veksha/cuda_hotspots#2]
![Screenshot from 2024-01-06 12-53-12](https://github.com/veksha/cuda_hotspots/assets/4154978/9a315430-1ccb-4e78-86d5-f5ab24662e83)

**Comment by veksha** [comment]
maybe try to close the file and reopen again, or reopen Cud.
`history files.json` file is saved by CudaText code with a delay (interval). maybe that is the reason.

can we trigger saving of this `history files.json` file from plugin?

**Comment by Alexey-T** [comment]
now saving of bkmks is here

`Frame.DoSaveHistory(Ed); ` is in

- `procedure TfmMain.UpdateMenuRecent`
- `function TEditorFrame.DoFileReload`

**Comment by Alexey-T** [comment]
>can we trigger

no yet.

**Comment by veksha** [comment]
so all we can do for now is to place bookmarks, then reload file or Cud, and then use them. personally it's ok for me.
tell me if you can add new api.

**Comment by Alexey-T** [comment]
u dont want to enumerate all ui-tabs and do this?

```
>>> ed.bookmark(BOOKMARK_GET_ALL, 0)
[{'line': 1, 'tag': 0, 'kind': 1, 'hint': '', 'auto_del': False, 'auto_delx': 2, 'show_in_list': True}, {'line': 2, 'tag': 0, 'kind': 1, 'hint': '', 'auto_del': False, 'auto_delx': 2, 'show_in_list': True}, {'line': 3, 'tag': 0, 'kind': 1, 'hint': '', 'auto_del': False, 'auto_delx': 2, 'show_in_list': True}]
```

**Comment by veksha** [comment]
yes. i will try.

**Comment by veksha** [comment]
fixed: https://github.com/veksha/cuda_hotspots/commit/9a524d6a906cdfd5a36c8751a985ec9bb30b1f4c
please, try again.
