### ISSUE TITLE
from Markus F in email

### ISSUE THREAD

**Issue by Alexey-T** [veksha/cuda_hotspots#20]
Some remarks on that one:
Why does the flashlight show out of the window? I think the flashlight
should show TOWARDS the hotspot panel rather than FROM it (see
screenshot). I for myself have flipped the icon horizontally, maybe you
have some use for it.

Furthermore, I added a 'hotspots' icon for the sideicons common_20x20
(see other screenshot), maybe you have some use for it too.

![panel_hotspots](https://github.com/veksha/cuda_hotspots/assets/4154978/c0ed6132-bd32-4b32-ac29-95234bae1ce6)

![common-hotspots](https://github.com/veksha/cuda_hotspots/assets/4154978/2627031f-0f26-4b8e-9124-3e7329564c3f)

---

[common_20x20.zip](https://github.com/veksha/cuda_hotspots/files/13853875/common_20x20.zip)

**Comment by Alexey-T** [comment]
from me: let's use Markus' icon from .zip file.

**Comment by veksha** [comment]
cool. thanks Markus. added.
