### ISSUE TITLE
hotspot - row content + filename /request…/

### ISSUE THREAD

**Issue by MiroslavMatas** [veksha/cuda_hotspots#21]
I am not sure if it is possible on this plugin… but it is possible on bookmarks + Cuda-Ext

to show not only filename + row number , but also line text… (even not whole line…)

right now - I can see that file BlaBla.mkd have 7 hotspots, but have no idea what is related to what… 
on the Cuda-Ext dialog - here is possible to see bookmarked line content + file name… and is possible to filter/search by text on row…

so, question - will be possible to implement that feature here?

![image](https://github.com/veksha/cuda_hotspots/assets/42316770/3683b162-fdb9-4048-b348-ec0db52cbe39)

**Comment by veksha** [comment]
implemented, please test

**Comment by Alexey-T** [comment]
hm. some bug: now, when I call (just after app start) 'go to hotsport' dlg, i get 'No hotspots'. but I have em - 2 bookmarks in user.json

**Comment by veksha** [comment]
"user.json" ?

**Comment by veksha** [comment]
please show those lines, do they have relative paths?

**Comment by Alexey-T** [comment]
![Screenshot from 2024-01-07 19-52-13](https://github.com/veksha/cuda_hotspots/assets/4154978/0cd7a8cc-c1f4-401b-a58b-9d14e4a30301)

text

```
  "bookmarks" : {
    "~|.config|cudatext|settings|user.json" : "5,1 6,1"
  },
```

**Comment by veksha** [comment]
cant reproduce... running on linux now. same bookmarks.

**Comment by Alexey-T** [comment]
hehe.
i added 'print' here
```
                    print('fpa:', fpath_abs)
                    if line is not None and os.path.isfile(fpath_abs):
                        bookmarks.append((fpath_abs, line, 1, read_specific_line(fpath_abs, line)))
```
it shows this
```
fpa: /home/user/~/.config/cudatext/settings/user.json
```

**Comment by veksha** [comment]
[bookmarks1.webm](https://github.com/veksha/cuda_hotspots/assets/275333/b0d96420-7c92-4e96-9149-78ea1087a8a7)

**Comment by Alexey-T** [comment]
i shown that the `fpath_abs` value is wrong. so you need to fix it...

**Comment by Alexey-T** [comment]
what i fixed, so it is OK now.
```
            for k, v in bookmarks_json['bookmarks'].items():
                fpath = k.replace("|", os.path.sep)
                fpath_abs = os.path.expanduser(fpath) # <------- HERE
```

**Comment by veksha** [comment]
seems that abspath will not replace expanduser as i thought. fixed.
