### ISSUE TITLE
After Diff head option, the tab caption changed to Diff:..

### ISSUE THREAD

**Issue by JairoMartinezA** [veksha/cuda_hotspots#22]
Hi @veksha

Basically
1. Collect hotspots in git folder
2. Over a modified file, use Diff head contextual menu option
3. Is opened a new tab with Diff lexer
4. Close this later tab
5. Open again the file with double clic
6. The tab caption always shows now:

![image](https://github.com/veksha/cuda_hotspots/assets/5806694/57943b3b-b1c8-498d-b60a-c4fc6e7bd138)

**Comment by veksha** [comment]
no repro on Windows. maybe this is macOS only CudaText bug?

https://github.com/veksha/cuda_hotspots/assets/275333/b140390e-a69d-41d9-bdd8-26b291ffeaef

**Comment by veksha** [comment]
try this command in CudaText console. it will create new tab, set title/lexer, close tab and reopen recent.
what tab title you will get?
```
import cudatext_cmd as cmds; ed.cmd(cmds.cmd_FileNew); ed.set_prop(PROP_TAB_TITLE, 'Diff: filepath..'); ed.set_prop(PROP_LEXER_FILE, 'Diff'); ed.cmd(cmds.cmd_FileClose); ed.cmd(cmds.cmd_FileReopenRecent)
```

**Comment by veksha** [comment]
reproduced on macOS vm.
this on macOS will first rename current tab title and then creates new tab (BUG?)
```
from cudatext_cmd import *; ed.cmd(cmd_FileNew); ed.set_prop(PROP_TAB_TITLE, "Diff: ...")
```
but on Windows/Linux: new tab is created and then renamed.
@Alexey-T

**Comment by Alexey-T** [comment]
What is bug repro?
I run in console:
```
from cudatext_cmd import *; ed.cmd(cmd_FileNew); ed.set_prop(PROP_TAB_TITLE, "Diff: ...")
```
on Linux I see that new tab has title 'Diff...'. what is bad?

**Comment by veksha** [comment]
bug is on macOS, not on Linux.

**Comment by veksha** [comment]
workaround attempt: https://github.com/veksha/cuda_hotspots/commit/398adf309a232c77cb28a4ce58ed8b7124d20437
please pull latest changes and try again, @JairoMartinezA 
now diff action must not use current tab.

If you still have "Diff: ..." this is because it is saved inside "history files.json" as "cap" key.
the workaround must work: diff output  will use new tab instead of current.

@Alexey-T question: how can we easily forget tab title saved in "cap" key in "history files.json"? clearing Recent Files command will do it, but it also clears Bookmarks! (is it OK? i don't think so)

**Comment by Alexey-T** [comment]
either clear tab title via API, or clear the history. yes, it clears bookmarks.

**Comment by veksha** [comment]
then maybe it should be renamed to "Clear recent files and bookmarks"?
or be split into two commands.

**Comment by Alexey-T** [comment]
code of clearing is doing simple deletion of file. not easy to change it to delete only some JSON keys. so i will rename to 'clear recent files+bookmarks'.

**Comment by veksha** [comment]
@JairoMartinezA changed workaround to use timer instead of app_idle(True). I tested - all ok. can you test?

**Comment by veksha** [comment]
> why using ed.cmd(cmds.cmd_FileNew) if we have file_open('') ? pls test the latter. if not ok, i will try to fix it

@Alexey-T , changed and it works good on macOS! (updated both of my plugins with this change)

PS: why it works differently? file_open  and cmd_FileNew

**Comment by Alexey-T** [comment]
cmd_FileNew runs this

formmain.pas
```
procedure TfmMain.DoFileNew;
var
  Frame: TEditorFrame;
begin
  Frame:= DoFileOpen('', '');
  DoApplyNewdocLexer(Frame);

  //ProcessMsg is only needed for macOS (so plugin API will update 'ed' to new tab),
  //but no harm for other OSes
  Application.ProcessMessages;
end;
```
here I added ProcessMessages- better?

**Comment by veksha** [comment]
i will test later.

**Comment by JairoMartinezA** [comment]
Excuse me Team, timezones differences of the flat earth 😸 I am getting up of bed. 

Testing.

---
UPDATE
@veksha I had to "clean" `history files.json` but with last changes all is working well.

**Comment by veksha** [comment]
> here I added ProcessMessages- better?

@Alexey-T 

file_open('') - works
ed.cmd(cmds.cmd_FileNew) - still doesn't work

**Comment by Alexey-T** [comment]
let's try here:

app/proc_cmd.pas, comment `cmd_FileNew`:
```
function IsCommandNeedTimer(Cmd: integer): boolean;
begin
  if Cmd<cmdFirstAppCommand then exit(false);
  if Cmd>cmdLastAppCommand then exit(false);

  case Cmd of
    cmdFirstLexerCommand..cmdLastLexerCommand,
    cmdFirstPluginCommand..cmdLastPluginCommand,
    cmdFirstPluginSubCommand..cmdLastPluginSubCommand,
    cmdFirstFileCommand..cmdLastFileCommand,
    cmdFirstRecentCommand..cmdLastRecentCommand:
      Result:= true;

    //cmd_FileNew, //don't need timer
    cmd_FileNewMenu, 
```

**Comment by Alexey-T** [comment]
I pushed this new fix to git. pull + try it.

**Comment by veksha** [comment]
yes, this is it!
