### ISSUE TITLE
error when I just edited WIkimedia file w/o using plugin at all

### ISSUE THREAD

**Issue by Alexey-T** [veksha/cuda_hotspots#3]
![Screenshot from 2024-01-06 13-34-23](https://github.com/veksha/cuda_hotspots/assets/4154978/b6458355-5366-4822-b9a3-8fe32368e884)

**Comment by veksha** [comment]
sidebar was not initialized, while you saved file and triggered collect hotspots action.
fixed: https://github.com/veksha/cuda_hotspots/commit/371d0df4ed0405b89c8c4519ab1da68dd1cb8015
