### ISSUE TITLE
bookmarks are reversed in order

### ISSUE THREAD

**Issue by Alexey-T** [veksha/cuda_hotspots#4]
![Screenshot from 2024-01-06 16-02-10](https://github.com/veksha/cuda_hotspots/assets/4154978/07ded98f-1e45-4c60-b5fc-93bcddb71d8d)

**Comment by Alexey-T** [comment]
- file, 140
- file, 139
- untitled, 4
- untitled, 3

**Comment by veksha** [comment]
fixed: https://github.com/veksha/cuda_hotspots/commit/26da22a616dc16dfd42af3b1903079cab0a25dae

reversed bookmark line order, but files with fresh bookmarks will still appear near the top. (it is convenient to see fresh ones at the top). ok?

**Comment by veksha** [comment]
now must be:
file, 139
file, 140
untitled, 3
untitled, 4

**Comment by Alexey-T** [comment]
my fresh bookmark (file not saved yet) on line 142 is shown ordered, after line 140 (old bookmark).

**Comment by Alexey-T** [comment]
files on top- as you wish.
