### ISSUE TITLE
fill .inf file lines

### ISSUE THREAD

**Issue by Alexey-T** [veksha/cuda_hotspots#6]
```
[info]
title=Hotspots
desc=Gives panel to show all existing bookmarks to jump to; also shows Git untracked files
type=cudatext-plugin
subdir=cuda_hotspots
homepage=https://github.com/veksha/cuda_hotspots
```

**Comment by veksha** [comment]
also shows git modified and untracked files

**Comment by Alexey-T** [comment]
ok

**Comment by MiroslavMatas** [comment]
> show all existing bookmarks

all existing - not related to Session, not related to Project… just simple all existing
am I right?

Q2: Numbered Bookmarks also?

**Comment by Alexey-T** [comment]
yes, all existing found in 'history session.json' and opened tabs.
numbered too (but I did not test, i only guess it).

**Comment by veksha** [comment]
fixed: https://github.com/veksha/cuda_hotspots/commit/578e5c69ff56d769274e68152ab23baa04b99904

**Comment by Alexey-T** [comment]
ops.
```
                        for h in ed_handles():
                            e = Editor(h)
                            if handle == h:
```
ed_handles gives VIRTUAL handles (numbers like 10...100). if you compare it to real handle (memory address) it is bad. so pls revert?

**Comment by veksha** [comment]
>  if you compare it to real handle

i'm not comparing to real handle, i think.
i don't understand. it works fine now. i'm not using PROP_HANDLE_SELF.

**Comment by Alexey-T** [comment]
you have `handle = ...` , it is some big int number. memory address of editor. yes?
then you compare it to `h` - virtual handles from `ed_handles` (small numbers like 10...20). yes?

**Comment by veksha** [comment]
handle is virtual too. obtained from same `ed_handles` method.

**Comment by Alexey-T** [comment]
ah, you right.
i added 
```
                        handle = int(fpath)
                        print('handle', handle)
```
and i see it is e.g. 12.
